name: Teste Action com Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Codigo
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalando Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testar
        run: |
          pytest